# Generated by Django 4.1.6 on 2023-02-09 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_Url', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('manf_date', models.IntegerField()),
                ('accessories', models.ManyToManyField(to='main_app.accessory')),
            ],
        ),
        migrations.CreateModel(
            name='Played',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Played on')),
                ('played', models.CharField(choices=[('A', '15 mins'), ('B', '30 mins'), ('C', '1 hour'), ('D', '1.5 hours'), ('E', '2 hours')], default='A', max_length=1)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.instrument')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
