# Generated by Django 4.1.3 on 2022-11-16 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('played', models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], default='N', max_length=1)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.instrument')),
            ],
        ),
    ]
