# Generated by Django 4.1.3 on 2022-11-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_accessory_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='played',
            name='date',
            field=models.DateField(verbose_name='Played on'),
        ),
        migrations.AlterField(
            model_name='played',
            name='played',
            field=models.CharField(choices=[('A', '15 mins'), ('B', '30 mins'), ('C', '1 hour'), ('D', '1.5 hours'), ('E', '2 hours')], default='A', max_length=1),
        ),
    ]
