# Generated by Django 4.1.3 on 2022-11-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_played_date_alter_played_played'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='played',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='instrument',
            name='accessories',
            field=models.ManyToManyField(to='main_app.accessory'),
        ),
    ]
