# Generated by Django 4.1.3 on 2022-11-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_accessory_alter_played_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='img_Url',
            field=models.CharField(default='https://i.imgur.com/hL0AvIC.jpg', max_length=50),
            preserve_default=False,
        ),
    ]
